spring:
  application:
    name: stockflow
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/stockflow
  cloud:
    function:
      definition: aiAnalysisInput
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 5s
    stream:
      defaultBinder: rabbit
      bindings:
        aiAnalysisInput-in-0:
          destination: ai.analysis.completed
          group: stockflow-service
          content-type: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/stockflow
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hibernate.jdbc.time_zone: America/Sao_Paulo
    hibernate:
      ddl-auto: create
server:
  port: 8080


resilience4j:
  retry:
    instances:
      remoteCall:
        maxAttempts: 3
        waitDuration: 70ms
  circuitbreaker:
    instances:
      remoteCall:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10ms
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      remoteCall:
        timeoutDuration: 100ms
        cancelRunningFuture: true