spring:
  application:
    name: stockflow
  security:
    oauth2:
      resourceserver:
        jwt:
        issuer-uri: http://keycloak-cluster.stockflow.svc.cluster.local:8000/realms/stockflow
  rabbitmq:
    host: rabbitmq-cluster.stockflow.svc.cluster.local
    port: 5672
    username: ${RABBIT_USER:admin_user}
    password: ${RABBIT_PASS:admin_pass}
  cloud:
    function:
      definition: aiAnalysisInput
    consul:
      host: consul-node.stockflow.svc.cluster.local
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 5s
        instance-id: ${spring.application.name}:${server.port}:${random.value[6]}
    stream:
      defaultBinder: rabbit
      bindings:
        aiAnalysisInput-in-0:
          destination: ai.analysis.completed
          group: stockflow-service
          content-type: application/json
  datasource:
    url: jdbc:postgresql://postgresql-cluster.stockflow.svc.cluster.local:5432/stockflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hibernate.jdbc.time_zone: America/Sao_Paulo
    hibernate:
      ddl-auto: create
server:
  port: 8080


resilience4j:
  retry:
    instances:
      remoteCall:
        maxAttempts: 3
        waitDuration: 70ms
  circuitbreaker:
    instances:
      remoteCall:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10ms
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      remoteCall:
        timeoutDuration: 100ms
        cancelRunningFuture: true