version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: housemanager_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: stockflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: housemanager_keycloack
    command: ["start-dev", "--http-enabled=true", "--hostname-strict=false", "--hostname-strict-https=false"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - 8000:8080
      - 8443:8443
    volumes:
      - keycloak_data:/opt/keycloak/data
  consul:
    image: hashicorp/consul:1.19
    container_name: housemanager_consul
    command:
      - agent
      - -dev
      - -ui
      - -client=0.0.0.0
      - -bind=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost/v1/status/leader" ]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  postgres_data:
  keycloak_data:
